### ISSUE TITLE
Update NuGet Version to 2.0.0

### ISSUE THREAD

**Issue by Pokerkoffer** [PureMVC/puremvc-csharp-multicore-framework#3]
Hello,
currently there is only version 1.0.0 available on Nuget, can you update it to version 2?
https://www.nuget.org/packages/PureMVC

Thanks.

**Comment by saadshams** [comment]
Nuget package versions are in sync. New package ids are as follows:

PureMVC Standard `dotnet add package PureMVC`

PureMVC Multicore `dotnet add package PureMVC.Multicore`

PureMVC Multicore Pipes `dotnet add package PureMVC.Multicore.Pipes`
