### ISSUE TITLE
PureMVC\Core\Model.cs(50,54): error CS1503: Argument 1: cannot convert from 'PureMVC.Core.Model' to 'bool'

### ISSUE THREAD

**Issue by scc172fly** [PureMVC/puremvc-csharp-multicore-framework#6]
#region Assembly mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// D:\Program Files\mono\4.7.1-api\mscorlib.dll
#endregion

public Model(string key)
 {
        multitonKey = key;
        InstanceMap.TryAdd(key, new Lazy<IModel>(this));
        proxyMap = new ConcurrentDictionary<string, IProxy>();
        InitializeModel();
}
PureMVC\Core\Model.cs(50,54): error CS1503: Argument 1: cannot convert from 'PureMVC.Core.Model' to 'bool'

It is amended as follows：
 public Model(string key)
 {
        multitonKey = key;
        InstanceMap.TryAdd(key, new Lazy<IModel>(() => this));
        proxyMap = new ConcurrentDictionary<string, IProxy>();
        InitializeModel();
 }

Facade.cs Model.cs View.cs Controller.cs There are similar situations.

**Comment by saadshams** [comment]
@scc172fly fixed applied. Thanks for your input.
